variables:
    SCHEMATIC: "pcb/*.kicad_sch"
    BOARD: "pcb/*.kicad_pcb"
    PROJECT: "pcb/*.kicad_pro"
    OUTDIR: "pcb"

default:
  timeout: 5m
  image: setsoft/kicad_auto:dev_k6
  artifacts:
    exclude:
    - $OUTDIR/**/*.ogv
 
stages:
  - check
  - export
  - publish
 
# JOBS
 
# runs design checks
ERC:
  stage: check
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/erc.kibot.yaml" -vv
  artifacts:
    when: always
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
     - $OUTDIR/*-erc.txt
 
DRC:
  stage: check
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/drc.kibot.yaml" -vv
  allow_failure: true
  artifacts:
    when: always
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
      - $OUTDIR/*-drc.txt
 
# generates documentation
docs:
  needs: [ERC]
  stage: export
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/docs.kibot.yaml" -v
  allow_failure: true
  artifacts:
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
      - $OUTDIR/docs/*.pdf
      - $OUTDIR/docs/bom/*.html
      - $OUTDIR/img/*.svg
 
# generates images of board
cad:
  needs: [DRC]
  stage: export
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/cad.kibot.yaml" -v
  allow_failure: true
  artifacts:
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
      - $OUTDIR/img/**/*.svg

render:
  needs: [DRC]
  stage: export
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/render.kibot.yaml" -v
  allow_failure: true
  artifacts:
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
      - $OUTDIR/img/**/*.png

# generates fabrication files if commit tagged
gerbers:
  needs: [DRC]
  stage: export
  script:
      - kibot -d $OUTDIR -e $SCHEMATIC -b $BOARD -c ".kibot/gerbers.kibot.yaml" -v
  allow_failure: false
  artifacts:
    name: "CI_PROJECT_NAME $CI_JOB_NAME"
    paths:
      - $OUTDIR/gerbers/*.gbr
      - $OUTDIR/gerbers/*.drl
      - $OUTDIR/gerbers/*.csv

# upload assets
upload:
  needs: [gerbers, docs]
  stage: publish
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - zip $OUTDIR/$CI_PROJECT_NAME".zip" $OUTDIR/gerbers/*
  artifacts:
    name: "$CI_PROJECT_NAME $CI_COMMIT_TAG"
    paths:
      - $OUTDIR/docs/*
      - $OUTDIR/img/*
      - $OUTDIR/gerbers/*
      - $OUTDIR/*.pro
      - $OUTDIR/*.kicad_sch
      - $OUTDIR/*.kicad_pcb
      - $OUTDIR/*.lib
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
