name: "Preflight"

on:
  push:
  pull_request:
    paths:
      - ".*.sch"
      - ".*.kicad_pcb"
      - ".kibot/*.kibot.yaml"
      - ".github/workflows/*.yml"

env:
  OutputFolder: KiBotOutput
  Project: ${{ github.event.repository.name }}

jobs:
  Kibot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Get the commit hash.
      - name: Get GitHub commit hash
        id: vars
        run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"

      # Run KiBot with the preflight script
      - uses: INTI-CMNB/KiBot@master
        with:
          config: .kibot/preflight.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ env.Project }}.sch
          board: ${{ env.Project }}.kicad_pcb
          verbose: 2

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive logfile artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.Project }}-${{ steps.vars.outputs.commit }}-preflight
          path: ${{ env.OutputFolder }}/**.txt
